CREATE_LOGGEDIN = '''
    CREATE TABLE IF NOT EXISTS loggedin (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL UNIQUE,
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
'''
